[package]
name = "chain-service"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12"
prost = "0.13"
prost-types = "0.13"
tokio = { version = "1", features = ["full"] }
alloy = { version = "0.8", features = [
    "providers",
    "provider-http",
    "transports",
    "network",
    "sol-types",
    "contract",
    "rpc-types",
] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
dotenvy = "0.15"
anyhow = "1"
thiserror = "2"

[build-dependencies]
tonic-build = "0.12"
